==1452== Memcheck, a memory error detector
==1452== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==1452== Using Valgrind-3.10.0.SVN and LibVEX; rerun with -h for copyright info
==1452== Command: python test/py_test.py
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x56E90A: PyObject_GC_Del (in /usr/bin/python2.7)
==1452==    by 0x538FC6: ??? (in /usr/bin/python2.7)
==1452==    by 0x54B7B5: ??? (in /usr/bin/python2.7)
==1452==    by 0x579F2C: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==  Address 0x5df7020 is 2,688 bytes inside a block of size 2,731 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x585D8A: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==1452==    by 0x585DBD: ??? (in /usr/bin/python2.7)
==1452==    by 0x579EC4: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x54B76E: ??? (in /usr/bin/python2.7)
==1452==    by 0x579F2C: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452==  Address 0x5e4b020 is 1,520 bytes inside a block of size 2,494 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x585D8A: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==1452==    by 0x585DBD: ??? (in /usr/bin/python2.7)
==1452==    by 0x579EC4: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x54B76E: ??? (in /usr/bin/python2.7)
==1452==    by 0x538FE2: ??? (in /usr/bin/python2.7)
==1452==    by 0x54B791: ??? (in /usr/bin/python2.7)
==1452==    by 0x579F2C: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==  Address 0x5e3a020 is 144 bytes inside a block of size 464 free'd
==1452==    at 0x4C2CE8E: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x4E5C58: PyList_Append (in /usr/bin/python2.7)
==1452==    by 0x4A3DD3: ??? (in /usr/bin/python2.7)
==1452==    by 0x4A3F09: ??? (in /usr/bin/python2.7)
==1452==    by 0x4A40AF: ??? (in /usr/bin/python2.7)
==1452==    by 0x4A3FA7: ??? (in /usr/bin/python2.7)
==1452==    by 0x4A4085: ??? (in /usr/bin/python2.7)
==1452==    by 0x585CD5: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==1452==    by 0x585D7F: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==1452==    by 0x585DBD: ??? (in /usr/bin/python2.7)
==1452==    by 0x579EC4: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x56E90A: PyObject_GC_Del (in /usr/bin/python2.7)
==1452==    by 0x538FC6: ??? (in /usr/bin/python2.7)
==1452==    by 0x54B791: ??? (in /usr/bin/python2.7)
==1452==    by 0x579F2C: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==  Address 0x5dec020 is 10,448 bytes inside a block of size 11,567 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x585D8A: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==1452==    by 0x585DBD: ??? (in /usr/bin/python2.7)
==1452==    by 0x579EC4: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x56E90A: PyObject_GC_Del (in /usr/bin/python2.7)
==1452==    by 0x54B87B: ??? (in /usr/bin/python2.7)
==1452==    by 0x579F2C: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452==  Address 0x5def020 is 1,248 bytes inside a block of size 1,384 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x539994: ??? (in /usr/bin/python2.7)
==1452==    by 0x585CF8: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==1452==    by 0x585D7F: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==1452==    by 0x585DBD: ??? (in /usr/bin/python2.7)
==1452==    by 0x579EC4: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x54B86D: ??? (in /usr/bin/python2.7)
==1452==    by 0x579F2C: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452==  Address 0x5f30020 is 848 bytes inside a block of size 4,784 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x539994: ??? (in /usr/bin/python2.7)
==1452==    by 0x585CF8: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==1452==    by 0x585D7F: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==1452==    by 0x585DBD: ??? (in /usr/bin/python2.7)
==1452==    by 0x579EC4: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452== 
==1452== Conditional jump or move depends on uninitialised value(s)
==1452==    at 0x540017: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x538954: PyGrammar_AddAccelerators (in /usr/bin/python2.7)
==1452==    by 0x52B852: ??? (in /usr/bin/python2.7)
==1452==    by 0x52BE22: PyParser_ASTFromString (in /usr/bin/python2.7)
==1452==    by 0x52BFFB: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452== 
==1452== Use of uninitialised value of size 8
==1452==    at 0x54002F: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x538954: PyGrammar_AddAccelerators (in /usr/bin/python2.7)
==1452==    by 0x52B852: ??? (in /usr/bin/python2.7)
==1452==    by 0x52BE22: PyParser_ASTFromString (in /usr/bin/python2.7)
==1452==    by 0x52BFFB: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x538954: PyGrammar_AddAccelerators (in /usr/bin/python2.7)
==1452==    by 0x52B852: ??? (in /usr/bin/python2.7)
==1452==    by 0x52BE22: PyParser_ASTFromString (in /usr/bin/python2.7)
==1452==    by 0x52BFFB: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==  Address 0x5f71020 is 16 bytes before a block of size 676 alloc'd
==1452==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x53843F: PyGrammar_AddAccelerators (in /usr/bin/python2.7)
==1452==    by 0x52B852: ??? (in /usr/bin/python2.7)
==1452==    by 0x52BE22: PyParser_ASTFromString (in /usr/bin/python2.7)
==1452==    by 0x52BFFB: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x5BB270: ??? (in /usr/bin/python2.7)
==1452==    by 0x515136: ??? (in /usr/bin/python2.7)
==1452==    by 0x4AFC90: ??? (in /usr/bin/python2.7)
==1452==    by 0x479895: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C2FB: ??? (in /usr/bin/python2.7)
==1452==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==1452==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==  Address 0x5fdb020 is 33,744 bytes inside a block of size 36,032 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x52B594: ??? (in /usr/bin/python2.7)
==1452==    by 0x52BE22: PyParser_ASTFromString (in /usr/bin/python2.7)
==1452==    by 0x52BFFB: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x573D7A: ??? (in /usr/bin/python2.7)
==1452==    by 0x47E0B0: PyAST_Compile (in /usr/bin/python2.7)
==1452==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==  Address 0x5fdc020 is 688 bytes inside a block of size 768 free'd
==1452==    at 0x4C2CE8E: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x515136: ??? (in /usr/bin/python2.7)
==1452==    by 0x4AFC90: ??? (in /usr/bin/python2.7)
==1452==    by 0x479895: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C2FB: ??? (in /usr/bin/python2.7)
==1452==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==1452==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x5BB270: ??? (in /usr/bin/python2.7)
==1452==    by 0x515136: ??? (in /usr/bin/python2.7)
==1452==    by 0x4AFC90: ??? (in /usr/bin/python2.7)
==1452==    by 0x477E66: ??? (in /usr/bin/python2.7)
==1452==    by 0x477F7A: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C2C0: ??? (in /usr/bin/python2.7)
==1452==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==1452==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==  Address 0x6014020 is 384 bytes inside a block of size 768 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x5392BC: ??? (in /usr/bin/python2.7)
==1452==    by 0x4A9938: ??? (in /usr/bin/python2.7)
==1452==    by 0x4C88F0: PySymtable_Build (in /usr/bin/python2.7)
==1452==    by 0x47E032: PyAST_Compile (in /usr/bin/python2.7)
==1452==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x573D7A: ??? (in /usr/bin/python2.7)
==1452==    by 0x47E0B0: PyAST_Compile (in /usr/bin/python2.7)
==1452==    by 0x46964C: ??? (in /usr/bin/python2.7)
==1452==    by 0x4699E2: PyRun_FileExFlags (in /usr/bin/python2.7)
==1452==    by 0x469F1B: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==1452==    by 0x46AB80: Py_Main (in /usr/bin/python2.7)
==1452==    by 0x5076EC4: (below main) (libc-start.c:287)
==1452==  Address 0x60a6020 is 592 bytes inside a block of size 768 free'd
==1452==    at 0x4C2CE8E: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x4AF42F: ??? (in /usr/bin/python2.7)
==1452==    by 0x477E94: ??? (in /usr/bin/python2.7)
==1452==    by 0x578BA3: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C2C0: ??? (in /usr/bin/python2.7)
==1452==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==1452==    by 0x46964C: ??? (in /usr/bin/python2.7)
==1452==    by 0x4699E2: PyRun_FileExFlags (in /usr/bin/python2.7)
==1452==    by 0x469F1B: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==1452==    by 0x46AB80: Py_Main (in /usr/bin/python2.7)
==1452==    by 0x5076EC4: (below main) (libc-start.c:287)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x579959: ??? (in /usr/bin/python2.7)
==1452==    by 0x46ADF1: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D15FC: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D1858: PyObject_CallMethod (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==  Address 0x60b7020 is 3,616 bytes inside a block of size 7,152 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x582CE6A: inflateEnd (in /lib/x86_64-linux-gnu/libz.so.1.2.8)
==1452==    by 0x435A9D: ??? (in /usr/bin/python2.7)
==1452==    by 0x502BDF: PyObject_CallFunction (in /usr/bin/python2.7)
==1452==    by 0x59DCF1: ??? (in /usr/bin/python2.7)
==1452==    by 0x57984F: ??? (in /usr/bin/python2.7)
==1452==    by 0x46ADF1: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D15FC: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D1858: PyObject_CallMethod (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x5BB270: ??? (in /usr/bin/python2.7)
==1452==    by 0x50C437: _PyString_Resize (in /usr/bin/python2.7)
==1452==    by 0x435AC6: ??? (in /usr/bin/python2.7)
==1452==    by 0x502BDF: PyObject_CallFunction (in /usr/bin/python2.7)
==1452==    by 0x59DCF1: ??? (in /usr/bin/python2.7)
==1452==    by 0x57984F: ??? (in /usr/bin/python2.7)
==1452==    by 0x46ADF1: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D15FC: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D1858: PyObject_CallMethod (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DD5A: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==  Address 0x60bb020 is 2,464 bytes inside a block of size 4,097 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x4CC6E3: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D37C: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DD5A: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452==    by 0x46AE66: ??? (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x5BB270: ??? (in /usr/bin/python2.7)
==1452==    by 0x50C437: _PyString_Resize (in /usr/bin/python2.7)
==1452==    by 0x435A5F: ??? (in /usr/bin/python2.7)
==1452==    by 0x502BDF: PyObject_CallFunction (in /usr/bin/python2.7)
==1452==    by 0x59DCF1: ??? (in /usr/bin/python2.7)
==1452==    by 0x57984F: ??? (in /usr/bin/python2.7)
==1452==    by 0x46ADF1: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D15FC: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D1858: PyObject_CallMethod (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D82F: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==  Address 0x60e9020 is 28,880 bytes inside a block of size 32,805 free'd
==1452==    at 0x4C2CE8E: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x50C437: _PyString_Resize (in /usr/bin/python2.7)
==1452==    by 0x435A5F: ??? (in /usr/bin/python2.7)
==1452==    by 0x502BDF: PyObject_CallFunction (in /usr/bin/python2.7)
==1452==    by 0x59DCF1: ??? (in /usr/bin/python2.7)
==1452==    by 0x57984F: ??? (in /usr/bin/python2.7)
==1452==    by 0x46ADF1: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D15FC: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D1858: PyObject_CallMethod (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D82F: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x59DD28: ??? (in /usr/bin/python2.7)
==1452==    by 0x57984F: ??? (in /usr/bin/python2.7)
==1452==    by 0x46ADF1: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D15FC: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D1858: PyObject_CallMethod (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D82F: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==  Address 0x60ca020 is 16 bytes before a block of size 568 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x50C405C: __fopen_internal (iofopen.c:94)
==1452==    by 0x4CC177: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D37C: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D82F: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452== 
==1452== Conditional jump or move depends on uninitialised value(s)
==1452==    at 0x5BB279: ??? (in /usr/bin/python2.7)
==1452==    by 0x5AC787: _PyObject_GC_Resize (in /usr/bin/python2.7)
==1452==    by 0x4F31AF: PyFrame_New (in /usr/bin/python2.7)
==1452==    by 0x52CE52: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452== 
==1452== Use of uninitialised value of size 8
==1452==    at 0x5BB28E: ??? (in /usr/bin/python2.7)
==1452==    by 0x5AC787: _PyObject_GC_Resize (in /usr/bin/python2.7)
==1452==    by 0x4F31AF: PyFrame_New (in /usr/bin/python2.7)
==1452==    by 0x52CE52: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x5BB270: ??? (in /usr/bin/python2.7)
==1452==    by 0x5AC787: _PyObject_GC_Resize (in /usr/bin/python2.7)
==1452==    by 0x4F31AF: PyFrame_New (in /usr/bin/python2.7)
==1452==    by 0x52CE52: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==  Address 0x5f13020 is 16 bytes before a block of size 736 alloc'd
==1452==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x517A39: _PyObject_GC_NewVar (in /usr/bin/python2.7)
==1452==    by 0x4F3142: PyFrame_New (in /usr/bin/python2.7)
==1452==    by 0x52CE52: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x56E90A: PyObject_GC_Del (in /usr/bin/python2.7)
==1452==    by 0x54B87B: ??? (in /usr/bin/python2.7)
==1452==    by 0x538FE2: ??? (in /usr/bin/python2.7)
==1452==    by 0x54B791: ??? (in /usr/bin/python2.7)
==1452==    by 0x579F2C: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==  Address 0x5f13020 is 16 bytes before a block of size 736 alloc'd
==1452==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x517A39: _PyObject_GC_NewVar (in /usr/bin/python2.7)
==1452==    by 0x4F3142: PyFrame_New (in /usr/bin/python2.7)
==1452==    by 0x52CE52: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452== 
==1452== Conditional jump or move depends on uninitialised value(s)
==1452==    at 0x56E915: PyObject_GC_Del (in /usr/bin/python2.7)
==1452==    by 0x54B87B: ??? (in /usr/bin/python2.7)
==1452==    by 0x538FE2: ??? (in /usr/bin/python2.7)
==1452==    by 0x54B791: ??? (in /usr/bin/python2.7)
==1452==    by 0x579F2C: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452== 
==1452== Use of uninitialised value of size 8
==1452==    at 0x56E92D: PyObject_GC_Del (in /usr/bin/python2.7)
==1452==    by 0x54B87B: ??? (in /usr/bin/python2.7)
==1452==    by 0x538FE2: ??? (in /usr/bin/python2.7)
==1452==    by 0x54B791: ??? (in /usr/bin/python2.7)
==1452==    by 0x579F2C: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x56E90A: PyObject_GC_Del (in /usr/bin/python2.7)
==1452==    by 0x54B87B: ??? (in /usr/bin/python2.7)
==1452==    by 0x579F2C: ??? (in /usr/bin/python2.7)
==1452==    by 0x46B0E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==  Address 0x6580020 is 448 bytes inside a block of size 544 free'd
==1452==    at 0x4C2CE8E: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x5AC787: _PyObject_GC_Resize (in /usr/bin/python2.7)
==1452==    by 0x4F31AF: PyFrame_New (in /usr/bin/python2.7)
==1452==    by 0x52CE52: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x5BB270: ??? (in /usr/bin/python2.7)
==1452==    by 0x472687: ??? (in /usr/bin/python2.7)
==1452==    by 0x4733C9: ??? (in /usr/bin/python2.7)
==1452==    by 0x530824: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452==    by 0x579F0E: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==1452==  Address 0x758a020 is 48 bytes inside a block of size 1,744 free'd
==1452==    at 0x4C2CE8E: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x50C437: _PyString_Resize (in /usr/bin/python2.7)
==1452==    by 0x472AA4: ??? (in /usr/bin/python2.7)
==1452==    by 0x4733C9: ??? (in /usr/bin/python2.7)
==1452==    by 0x530824: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452==    by 0x579F0E: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452== 
==1452== Conditional jump or move depends on uninitialised value(s)
==1452==    at 0x5BB279: ??? (in /usr/bin/python2.7)
==1452==    by 0x537DEC: PyParser_AddToken (in /usr/bin/python2.7)
==1452==    by 0x52B4B6: ??? (in /usr/bin/python2.7)
==1452==    by 0x52BE22: PyParser_ASTFromString (in /usr/bin/python2.7)
==1452==    by 0x52BFFB: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452==    by 0x579F0E: ??? (in /usr/bin/python2.7)
==1452== 
==1452== Use of uninitialised value of size 8
==1452==    at 0x5BB28E: ??? (in /usr/bin/python2.7)
==1452==    by 0x537DEC: PyParser_AddToken (in /usr/bin/python2.7)
==1452==    by 0x52B4B6: ??? (in /usr/bin/python2.7)
==1452==    by 0x52BE22: PyParser_ASTFromString (in /usr/bin/python2.7)
==1452==    by 0x52BFFB: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452==    by 0x579F0E: ??? (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x574286: ??? (in /usr/bin/python2.7)
==1452==    by 0x52BC2B: PyParser_ASTFromString (in /usr/bin/python2.7)
==1452==    by 0x52BFFB: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452==    by 0x579F0E: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==  Address 0x7597020 is 32,800 bytes inside a block of size 36,032 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x52B594: ??? (in /usr/bin/python2.7)
==1452==    by 0x52BE22: PyParser_ASTFromString (in /usr/bin/python2.7)
==1452==    by 0x52BFFB: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452==    by 0x579F0E: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x573D7A: ??? (in /usr/bin/python2.7)
==1452==    by 0x47A16D: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C3A3: ??? (in /usr/bin/python2.7)
==1452==    by 0x579252: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C403: ??? (in /usr/bin/python2.7)
==1452==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==1452==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==  Address 0x759f020 is 608 bytes inside a block of size 768 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x5392BC: ??? (in /usr/bin/python2.7)
==1452==    by 0x573EC3: ??? (in /usr/bin/python2.7)
==1452==    by 0x47A16D: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C3A3: ??? (in /usr/bin/python2.7)
==1452==    by 0x579252: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C403: ??? (in /usr/bin/python2.7)
==1452==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==1452==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x5BB270: ??? (in /usr/bin/python2.7)
==1452==    by 0x515136: ??? (in /usr/bin/python2.7)
==1452==    by 0x4AFC43: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C3A3: ??? (in /usr/bin/python2.7)
==1452==    by 0x579252: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C403: ??? (in /usr/bin/python2.7)
==1452==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==1452==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==  Address 0x759f020 is 608 bytes inside a block of size 768 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x5392BC: ??? (in /usr/bin/python2.7)
==1452==    by 0x573EC3: ??? (in /usr/bin/python2.7)
==1452==    by 0x47A16D: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C3A3: ??? (in /usr/bin/python2.7)
==1452==    by 0x579252: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C403: ??? (in /usr/bin/python2.7)
==1452==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==1452==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x5BB270: ??? (in /usr/bin/python2.7)
==1452==    by 0x4AF42F: ??? (in /usr/bin/python2.7)
==1452==    by 0x47986C: ??? (in /usr/bin/python2.7)
==1452==    by 0x477FFE: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C2C0: ??? (in /usr/bin/python2.7)
==1452==    by 0x579252: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C403: ??? (in /usr/bin/python2.7)
==1452==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==1452==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==  Address 0x75a1020 is 16 bytes inside a block of size 80 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x539994: ??? (in /usr/bin/python2.7)
==1452==    by 0x4A0323: ??? (in /usr/bin/python2.7)
==1452==    by 0x47A15C: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C3A3: ??? (in /usr/bin/python2.7)
==1452==    by 0x579252: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C403: ??? (in /usr/bin/python2.7)
==1452==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==1452==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x573D7A: ??? (in /usr/bin/python2.7)
==1452==    by 0x5A5092: ??? (in /usr/bin/python2.7)
==1452==    by 0x57929C: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C403: ??? (in /usr/bin/python2.7)
==1452==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==1452==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==  Address 0x75a1020 is 16 bytes inside a block of size 80 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x539994: ??? (in /usr/bin/python2.7)
==1452==    by 0x4A0323: ??? (in /usr/bin/python2.7)
==1452==    by 0x47A15C: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C3A3: ??? (in /usr/bin/python2.7)
==1452==    by 0x579252: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C403: ??? (in /usr/bin/python2.7)
==1452==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==1452==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x53A541: ??? (in /usr/bin/python2.7)
==1452==    by 0x55C5B8: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452==    by 0x579F0E: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==  Address 0x758a020 is 48 bytes inside a block of size 1,744 free'd
==1452==    at 0x4C2CE8E: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x50C437: _PyString_Resize (in /usr/bin/python2.7)
==1452==    by 0x472AA4: ??? (in /usr/bin/python2.7)
==1452==    by 0x4733C9: ??? (in /usr/bin/python2.7)
==1452==    by 0x530824: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452==    by 0x579F0E: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x574127: ??? (in /usr/bin/python2.7)
==1452==    by 0x5743F5: ??? (in /usr/bin/python2.7)
==1452==    by 0x52BC2B: PyParser_ASTFromString (in /usr/bin/python2.7)
==1452==    by 0x52BFFB: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452==    by 0x579F0E: ??? (in /usr/bin/python2.7)
==1452==  Address 0x75b5020 is 33,920 bytes inside a block of size 36,032 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x52B594: ??? (in /usr/bin/python2.7)
==1452==    by 0x52BE22: PyParser_ASTFromString (in /usr/bin/python2.7)
==1452==    by 0x52BFFB: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452==    by 0x579F0E: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x4A075A: ??? (in /usr/bin/python2.7)
==1452==    by 0x579291: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C403: ??? (in /usr/bin/python2.7)
==1452==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==1452==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452==  Address 0x75c2020 is 16 bytes inside a block of size 549 free'd
==1452==    at 0x4C2CE8E: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x50C437: _PyString_Resize (in /usr/bin/python2.7)
==1452==    by 0x49FF63: ??? (in /usr/bin/python2.7)
==1452==    by 0x579291: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C403: ??? (in /usr/bin/python2.7)
==1452==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==1452==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x5BB270: ??? (in /usr/bin/python2.7)
==1452==    by 0x50C437: _PyString_Resize (in /usr/bin/python2.7)
==1452==    by 0x472AA4: ??? (in /usr/bin/python2.7)
==1452==    by 0x4733C9: ??? (in /usr/bin/python2.7)
==1452==    by 0x530824: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452==  Address 0x774f020 is not stack'd, malloc'd or (recently) free'd
==1452== 
==1452== Conditional jump or move depends on uninitialised value(s)
==1452==    at 0x540017: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x573D7A: ??? (in /usr/bin/python2.7)
==1452==    by 0x47A16D: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C3A3: ??? (in /usr/bin/python2.7)
==1452==    by 0x579252: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C403: ??? (in /usr/bin/python2.7)
==1452==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==1452==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452== 
==1452== Use of uninitialised value of size 8
==1452==    at 0x54002F: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x573D7A: ??? (in /usr/bin/python2.7)
==1452==    by 0x47A16D: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C3A3: ??? (in /usr/bin/python2.7)
==1452==    by 0x579252: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C403: ??? (in /usr/bin/python2.7)
==1452==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==1452==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452== 
==1452== Conditional jump or move depends on uninitialised value(s)
==1452==    at 0x5BB279: ??? (in /usr/bin/python2.7)
==1452==    by 0x515136: ??? (in /usr/bin/python2.7)
==1452==    by 0x4AFC43: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C3A3: ??? (in /usr/bin/python2.7)
==1452==    by 0x579252: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C403: ??? (in /usr/bin/python2.7)
==1452==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==1452==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452== 
==1452== Use of uninitialised value of size 8
==1452==    at 0x5BB28E: ??? (in /usr/bin/python2.7)
==1452==    by 0x515136: ??? (in /usr/bin/python2.7)
==1452==    by 0x4AFC43: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C3A3: ??? (in /usr/bin/python2.7)
==1452==    by 0x579252: ??? (in /usr/bin/python2.7)
==1452==    by 0x47C403: ??? (in /usr/bin/python2.7)
==1452==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==1452==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==1452==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x53A516: ??? (in /usr/bin/python2.7)
==1452==    by 0x52CF52: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x56D0A9: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D9853: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D8378: ??? (in /usr/bin/python2.7)
==1452==    by 0x4F5D0A: ??? (in /usr/bin/python2.7)
==1452==    by 0x52E1E5: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x56D0A9: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D259B: ??? (in /usr/bin/python2.7)
==1452==    by 0x4F5BF4: ??? (in /usr/bin/python2.7)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==  Address 0x778f020 is 48 bytes inside a block of size 96 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x539994: ??? (in /usr/bin/python2.7)
==1452==    by 0x53A516: ??? (in /usr/bin/python2.7)
==1452==    by 0x52CF52: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x56D0A9: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D9853: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D8378: ??? (in /usr/bin/python2.7)
==1452==    by 0x4F5D0A: ??? (in /usr/bin/python2.7)
==1452==    by 0x52E1E5: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x56D0A9: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D259B: ??? (in /usr/bin/python2.7)
==1452==    by 0x4F5BF4: ??? (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x56E90A: PyObject_GC_Del (in /usr/bin/python2.7)
==1452==    by 0x517124: ??? (in /usr/bin/python2.7)
==1452==    by 0x4C27F3: PyType_GenericAlloc (in /usr/bin/python2.7)
==1452==    by 0x4C555B: ??? (in /usr/bin/python2.7)
==1452==    by 0x4F5BF4: ??? (in /usr/bin/python2.7)
==1452==    by 0x4B551F: PyErr_NormalizeException (in /usr/bin/python2.7)
==1452==    by 0x52F19C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x56CD29: ??? (in /usr/bin/python2.7)
==1452==    by 0x52C94D: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==  Address 0x77a5020 is 48 bytes inside a block of size 64 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x539994: ??? (in /usr/bin/python2.7)
==1452==    by 0x53A572: ??? (in /usr/bin/python2.7)
==1452==    by 0x55C5B8: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x54B76E: ??? (in /usr/bin/python2.7)
==1452==    by 0x46AE87: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D15FC: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D1858: PyObject_CallMethod (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D82F: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==  Address 0x6134020 is 106,368 bytes inside a block of size 107,196 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x579959: ??? (in /usr/bin/python2.7)
==1452==    by 0x46ADF1: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D15FC: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D1858: PyObject_CallMethod (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D82F: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x56E90A: PyObject_GC_Del (in /usr/bin/python2.7)
==1452==    by 0x538FC6: ??? (in /usr/bin/python2.7)
==1452==    by 0x54B791: ??? (in /usr/bin/python2.7)
==1452==    by 0x46AE87: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D15FC: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D1858: PyObject_CallMethod (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D82F: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==  Address 0x6134020 is 106,368 bytes inside a block of size 107,196 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x579959: ??? (in /usr/bin/python2.7)
==1452==    by 0x46ADF1: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D15FC: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D1858: PyObject_CallMethod (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D82F: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x56E90A: PyObject_GC_Del (in /usr/bin/python2.7)
==1452==    by 0x538FC6: ??? (in /usr/bin/python2.7)
==1452==    by 0x54B7B5: ??? (in /usr/bin/python2.7)
==1452==    by 0x46AE87: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D15FC: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D1858: PyObject_CallMethod (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D82F: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==  Address 0x640f020 is 6,000 bytes inside a block of size 6,168 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x539994: ??? (in /usr/bin/python2.7)
==1452==    by 0x585CF8: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==1452==    by 0x579A9B: ??? (in /usr/bin/python2.7)
==1452==    by 0x46ADF1: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D15FC: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D1858: PyObject_CallMethod (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D82F: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x56E90A: PyObject_GC_Del (in /usr/bin/python2.7)
==1452==    by 0x54B87B: ??? (in /usr/bin/python2.7)
==1452==    by 0x46AE87: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D15FC: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D1858: PyObject_CallMethod (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D82F: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==  Address 0x640f020 is 6,000 bytes inside a block of size 6,168 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x539994: ??? (in /usr/bin/python2.7)
==1452==    by 0x585CF8: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==1452==    by 0x579A9B: ??? (in /usr/bin/python2.7)
==1452==    by 0x46ADF1: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D15FC: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D1858: PyObject_CallMethod (in /usr/bin/python2.7)
==1452==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==1452==    by 0x55D82F: ??? (in /usr/bin/python2.7)
==1452==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==1452==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x53A572: ??? (in /usr/bin/python2.7)
==1452==    by 0x56CCE1: ??? (in /usr/bin/python2.7)
==1452==    by 0x52296F: ??? (in /usr/bin/python2.7)
==1452==    by 0x52CCBB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452==  Address 0x7c6a020 is 5,184 bytes inside a block of size 7,152 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x582CE6A: inflateEnd (in /lib/x86_64-linux-gnu/libz.so.1.2.8)
==1452==    by 0x435A9D: ??? (in /usr/bin/python2.7)
==1452==    by 0x502BDF: PyObject_CallFunction (in /usr/bin/python2.7)
==1452==    by 0x59DCF1: ??? (in /usr/bin/python2.7)
==1452==    by 0x43B1EB: ??? (in /usr/bin/python2.7)
==1452==    by 0x52C6D4: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452== 
/usr/local/lib/python2.7/dist-packages/setuptools-5.7-py2.7.egg/pkg_resources.py:1049: UserWarning: /home/massimo/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
==1452== Conditional jump or move depends on uninitialised value(s)
==1452==    at 0x540017: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x59DD28: ??? (in /usr/bin/python2.7)
==1452==    by 0x43B1EB: ??? (in /usr/bin/python2.7)
==1452==    by 0x52C6D4: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452== 
==1452== Use of uninitialised value of size 8
==1452==    at 0x54002F: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x59DD28: ??? (in /usr/bin/python2.7)
==1452==    by 0x43B1EB: ??? (in /usr/bin/python2.7)
==1452==    by 0x52C6D4: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x5BB270: ??? (in /usr/bin/python2.7)
==1452==    by 0x50C437: _PyString_Resize (in /usr/bin/python2.7)
==1452==    by 0x55310B: ??? (in /usr/bin/python2.7)
==1452==    by 0x52C6D4: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452==  Address 0x8c00020 is not stack'd, malloc'd or (recently) free'd
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x53A516: ??? (in /usr/bin/python2.7)
==1452==    by 0x52CF52: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452==    by 0x46AE66: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D15FC: ??? (in /usr/bin/python2.7)
==1452==  Address 0x8800020 is not stack'd, malloc'd or (recently) free'd
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x53A541: ??? (in /usr/bin/python2.7)
==1452==    by 0x52CF52: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452==    by 0x46AE66: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D15FC: ??? (in /usr/bin/python2.7)
==1452==  Address 0x9000020 is not stack'd, malloc'd or (recently) free'd
==1452== 
==1452== Conditional jump or move depends on uninitialised value(s)
==1452==    at 0x5BB279: ??? (in /usr/bin/python2.7)
==1452==    by 0x50C437: _PyString_Resize (in /usr/bin/python2.7)
==1452==    by 0x435A5F: ??? (in /usr/bin/python2.7)
==1452==    by 0x502BDF: PyObject_CallFunction (in /usr/bin/python2.7)
==1452==    by 0x59DCF1: ??? (in /usr/bin/python2.7)
==1452==    by 0x43B1EB: ??? (in /usr/bin/python2.7)
==1452==    by 0x52C6D4: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x59DD28: ??? (in /usr/bin/python2.7)
==1452==    by 0x43B1EB: ??? (in /usr/bin/python2.7)
==1452==    by 0x52C6D4: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452==  Address 0x7e06020 is 522,608 bytes inside a block of size 524,325 free'd
==1452==    at 0x4C2CE8E: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x50C437: _PyString_Resize (in /usr/bin/python2.7)
==1452==    by 0x435A5F: ??? (in /usr/bin/python2.7)
==1452==    by 0x502BDF: PyObject_CallFunction (in /usr/bin/python2.7)
==1452==    by 0x59DCF1: ??? (in /usr/bin/python2.7)
==1452==    by 0x43B1EB: ??? (in /usr/bin/python2.7)
==1452==    by 0x52C6D4: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x56E90A: PyObject_GC_Del (in /usr/bin/python2.7)
==1452==    by 0x517124: ??? (in /usr/bin/python2.7)
==1452==    by 0x517BDE: _PyObject_GC_NewVar (in /usr/bin/python2.7)
==1452==    by 0x50A571: PyTuple_New (in /usr/bin/python2.7)
==1452==    by 0x52D187: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x469662: ??? (in /usr/bin/python2.7)
==1452==    by 0x4699E2: PyRun_FileExFlags (in /usr/bin/python2.7)
==1452==    by 0x469F1B: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==1452==    by 0x46AB80: Py_Main (in /usr/bin/python2.7)
==1452==    by 0x5076EC4: (below main) (libc-start.c:287)
==1452==  Address 0x7863020 is 16 bytes after a block of size 12,288 alloc'd
==1452==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x527959: ??? (in /usr/bin/python2.7)
==1452==    by 0x52D7A2: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x56D0A9: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D9853: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D8378: ??? (in /usr/bin/python2.7)
==1452==    by 0x4F5D0A: ??? (in /usr/bin/python2.7)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452== 
TRAINING:
Num. users: 1000
Num. items: 1000
[NODE 0]: Num.users: 1000	Num.ratings: 10000	Quality: -10410.4
[NODE 0]: Splitter found in 6.489 sec.	Id: 942	Quality: -10153.6
==1452== Invalid write of size 8
==1452==    at 0x8C12AD4: std::vector<ABDIndex<unsigned long, ABDStats>::bound_t, std::allocator<ABDIndex<unsigned long, ABDStats>::bound_t> > ABDTree::sort_by_group<__gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > > >(__gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > >, __gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > >, unsigned long, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > > const&) (stl_algobase.h:336)
==1452==    by 0x8C0C19B: ABDTree::split(ABDNode*, unsigned long, double, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) (abd_tree.hpp:354)
==1452==    by 0x8C1576F: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:118)
==1452==    by 0x8C0D0D6: ABDTree::build() (abd_tree.hpp:317)
==1452==    by 0x8C0DF75: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ABDTree::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, ErrorTreePy&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94262C2: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==  Address 0x8161f40 is 0 bytes after a block of size 384 alloc'd
==1452==    at 0x4C2B0E0: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C10788: void std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> >::_M_emplace_back_aux<ScoreUnbiased const&>(ScoreUnbiased const&) (new_allocator.h:104)
==1452==    by 0x8C0DB26: ABDTree::init(std::vector<Rating, std::allocator<Rating> > const&) (stl_vector.h:923)
==1452==    by 0x8C11857: ErrorTreePy::init_py(boost::python::list const&) (dtreemodule.cpp:37)
==1452==    by 0x8C0E9C1: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ErrorTreePy::*)(boost::python::list const&), boost::python::default_call_policies, boost::mpl::vector3<void, ErrorTreePy&, boost::python::list const&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94262C2: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452== 
==1452== Invalid write of size 8
==1452==    at 0x8C12ADD: std::vector<ABDIndex<unsigned long, ABDStats>::bound_t, std::allocator<ABDIndex<unsigned long, ABDStats>::bound_t> > ABDTree::sort_by_group<__gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > > >(__gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > >, __gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > >, unsigned long, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > > const&) (stl_algobase.h:336)
==1452==    by 0x8C0C19B: ABDTree::split(ABDNode*, unsigned long, double, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) (abd_tree.hpp:354)
==1452==    by 0x8C1576F: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:118)
==1452==    by 0x8C0D0D6: ABDTree::build() (abd_tree.hpp:317)
==1452==    by 0x8C0DF75: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ABDTree::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, ErrorTreePy&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94262C2: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==  Address 0x8161f48 is 8 bytes after a block of size 384 alloc'd
==1452==    at 0x4C2B0E0: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C10788: void std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> >::_M_emplace_back_aux<ScoreUnbiased const&>(ScoreUnbiased const&) (new_allocator.h:104)
==1452==    by 0x8C0DB26: ABDTree::init(std::vector<Rating, std::allocator<Rating> > const&) (stl_vector.h:923)
==1452==    by 0x8C11857: ErrorTreePy::init_py(boost::python::list const&) (dtreemodule.cpp:37)
==1452==    by 0x8C0E9C1: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ErrorTreePy::*)(boost::python::list const&), boost::python::default_call_policies, boost::mpl::vector3<void, ErrorTreePy&, boost::python::list const&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94262C2: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452== 
==1452== Invalid write of size 8
==1452==    at 0x8C12AE7: std::vector<ABDIndex<unsigned long, ABDStats>::bound_t, std::allocator<ABDIndex<unsigned long, ABDStats>::bound_t> > ABDTree::sort_by_group<__gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > > >(__gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > >, __gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > >, unsigned long, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > > const&) (stl_algobase.h:336)
==1452==    by 0x8C0C19B: ABDTree::split(ABDNode*, unsigned long, double, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) (abd_tree.hpp:354)
==1452==    by 0x8C1576F: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:118)
==1452==    by 0x8C0D0D6: ABDTree::build() (abd_tree.hpp:317)
==1452==    by 0x8C0DF75: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ABDTree::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, ErrorTreePy&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94262C2: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==  Address 0x8161f50 is 16 bytes after a block of size 384 alloc'd
==1452==    at 0x4C2B0E0: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C10788: void std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> >::_M_emplace_back_aux<ScoreUnbiased const&>(ScoreUnbiased const&) (new_allocator.h:104)
==1452==    by 0x8C0DB26: ABDTree::init(std::vector<Rating, std::allocator<Rating> > const&) (stl_vector.h:923)
==1452==    by 0x8C11857: ErrorTreePy::init_py(boost::python::list const&) (dtreemodule.cpp:37)
==1452==    by 0x8C0E9C1: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ErrorTreePy::*)(boost::python::list const&), boost::python::default_call_policies, boost::mpl::vector3<void, ErrorTreePy&, boost::python::list const&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94262C2: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452== 
	[NODE 1]: Num.users: 6	Num.ratings: 71	Quality: -4.80121
	[NODE 1]: Splitter found in 0.401 sec.	Id: 830	Quality: -2.03346
		[NODE 4]: Num.users: 0	Num.ratings: 0	Quality: -0
		[NODE 4]: Maximum depth (3) reached. STOP.
		[NODE 5]: Num.users: 1	Num.ratings: 12	Quality: -2
		[NODE 5]: Maximum depth (3) reached. STOP.
		[NODE 6]: Num.users: 5	Num.ratings: 59	Quality: -0.0334595
		[NODE 6]: Maximum depth (3) reached. STOP.
	[NODE 2]: Num.users: 14	Num.ratings: 142	Quality: -16.4611
	[NODE 2]: Splitter found in 0.695 sec.	Id: 513	Quality: -11.767
		[NODE 7]: Num.users: 1	Num.ratings: 12	Quality: -2
		[NODE 7]: Maximum depth (3) reached. STOP.
		[NODE 8]: Num.users: 1	Num.ratings: 6	Quality: -0
		[NODE 8]: Maximum depth (3) reached. STOP.
		[NODE 9]: Num.users: 12	Num.ratings: 124	Quality: -9.76705
		[NODE 9]: Maximum depth (3) reached. STOP.
	[NODE 3]: Num.users: 980	Num.ratings: 9799	Quality: -10132.3
==1452== Thread 3:
==1452== Invalid read of size 8
==1452==    at 0x8C0C952: ABDTree::split_quality(ABDNode const*, unsigned long, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) const (abd_tree.hpp:377)
==1452==    by 0x8C0A981: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.1] (d_tree.hpp:160)
==1452==    by 0x840A64C: GOMP_task (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C0A91D: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.0] (d_tree.hpp:153)
==1452==    by 0x840C825: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x4E3F181: start_thread (pthread_create.c:312)
==1452==    by 0x515000C: clone (clone.S:111)
==1452==  Address 0x8161f48 is 8 bytes after a block of size 384 alloc'd
==1452==    at 0x4C2B0E0: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C10788: void std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> >::_M_emplace_back_aux<ScoreUnbiased const&>(ScoreUnbiased const&) (new_allocator.h:104)
==1452==    by 0x8C0DB26: ABDTree::init(std::vector<Rating, std::allocator<Rating> > const&) (stl_vector.h:923)
==1452==    by 0x8C11857: ErrorTreePy::init_py(boost::python::list const&) (dtreemodule.cpp:37)
==1452==    by 0x8C0E9C1: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ErrorTreePy::*)(boost::python::list const&), boost::python::default_call_policies, boost::mpl::vector3<void, ErrorTreePy&, boost::python::list const&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94262C2: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 8
==1452==    at 0x8C0C974: ABDTree::split_quality(ABDNode const*, unsigned long, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) const (new_allocator.h:120)
==1452==    by 0x8C0A981: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.1] (d_tree.hpp:160)
==1452==    by 0x840A64C: GOMP_task (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C0A91D: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.0] (d_tree.hpp:153)
==1452==    by 0x840C825: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x4E3F181: start_thread (pthread_create.c:312)
==1452==    by 0x515000C: clone (clone.S:111)
==1452==  Address 0x8161f40 is 0 bytes after a block of size 384 alloc'd
==1452==    at 0x4C2B0E0: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C10788: void std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> >::_M_emplace_back_aux<ScoreUnbiased const&>(ScoreUnbiased const&) (new_allocator.h:104)
==1452==    by 0x8C0DB26: ABDTree::init(std::vector<Rating, std::allocator<Rating> > const&) (stl_vector.h:923)
==1452==    by 0x8C11857: ErrorTreePy::init_py(boost::python::list const&) (dtreemodule.cpp:37)
==1452==    by 0x8C0E9C1: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ErrorTreePy::*)(boost::python::list const&), boost::python::default_call_policies, boost::mpl::vector3<void, ErrorTreePy&, boost::python::list const&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94262C2: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 8
==1452==    at 0x8C0C993: ABDTree::split_quality(ABDNode const*, unsigned long, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) const (abd_tree.hpp:383)
==1452==    by 0x8C0A981: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.1] (d_tree.hpp:160)
==1452==    by 0x840A64C: GOMP_task (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C0A91D: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.0] (d_tree.hpp:153)
==1452==    by 0x840C825: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x4E3F181: start_thread (pthread_create.c:312)
==1452==    by 0x515000C: clone (clone.S:111)
==1452==  Address 0x8161f40 is 0 bytes after a block of size 384 alloc'd
==1452==    at 0x4C2B0E0: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C10788: void std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> >::_M_emplace_back_aux<ScoreUnbiased const&>(ScoreUnbiased const&) (new_allocator.h:104)
==1452==    by 0x8C0DB26: ABDTree::init(std::vector<Rating, std::allocator<Rating> > const&) (stl_vector.h:923)
==1452==    by 0x8C11857: ErrorTreePy::init_py(boost::python::list const&) (dtreemodule.cpp:37)
==1452==    by 0x8C0E9C1: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ErrorTreePy::*)(boost::python::list const&), boost::python::default_call_policies, boost::mpl::vector3<void, ErrorTreePy&, boost::python::list const&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94262C2: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452== 
	[NODE 3]: Splitter found in 6.05 sec.	Id: 17	Quality: -9879.93
==1452== Thread 1:
==1452== Invalid read of size 8
==1452==    at 0x8C129C8: std::vector<ABDIndex<unsigned long, ABDStats>::bound_t, std::allocator<ABDIndex<unsigned long, ABDStats>::bound_t> > ABDTree::sort_by_group<__gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > > >(__gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > >, __gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > >, unsigned long, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > > const&) (abd_tree.hpp:434)
==1452==    by 0x8C0C19B: ABDTree::split(ABDNode*, unsigned long, double, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) (abd_tree.hpp:354)
==1452==    by 0x8C1576F: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:118)
==1452==    by 0x8C158DB: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:125)
==1452==    by 0x8C0D0D6: ABDTree::build() (abd_tree.hpp:317)
==1452==    by 0x8C0DF75: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ABDTree::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, ErrorTreePy&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94262C2: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==  Address 0x8161f40 is 0 bytes after a block of size 384 alloc'd
==1452==    at 0x4C2B0E0: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C10788: void std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> >::_M_emplace_back_aux<ScoreUnbiased const&>(ScoreUnbiased const&) (new_allocator.h:104)
==1452==    by 0x8C0DB26: ABDTree::init(std::vector<Rating, std::allocator<Rating> > const&) (stl_vector.h:923)
==1452==    by 0x8C11857: ErrorTreePy::init_py(boost::python::list const&) (dtreemodule.cpp:37)
==1452==    by 0x8C0E9C1: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ErrorTreePy::*)(boost::python::list const&), boost::python::default_call_policies, boost::mpl::vector3<void, ErrorTreePy&, boost::python::list const&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94262C2: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 8
==1452==    at 0x8C12BF5: std::vector<ABDIndex<unsigned long, ABDStats>::bound_t, std::allocator<ABDIndex<unsigned long, ABDStats>::bound_t> > ABDTree::sort_by_group<__gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > > >(__gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > >, __gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > >, unsigned long, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > > const&) (new_allocator.h:120)
==1452==    by 0x8C0C19B: ABDTree::split(ABDNode*, unsigned long, double, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) (abd_tree.hpp:354)
==1452==    by 0x8C1576F: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:118)
==1452==    by 0x8C158DB: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:125)
==1452==    by 0x8C0D0D6: ABDTree::build() (abd_tree.hpp:317)
==1452==    by 0x8C0DF75: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ABDTree::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, ErrorTreePy&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94262C2: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==  Address 0x8161f40 is 0 bytes after a block of size 384 alloc'd
==1452==    at 0x4C2B0E0: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C10788: void std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> >::_M_emplace_back_aux<ScoreUnbiased const&>(ScoreUnbiased const&) (new_allocator.h:104)
==1452==    by 0x8C0DB26: ABDTree::init(std::vector<Rating, std::allocator<Rating> > const&) (stl_vector.h:923)
==1452==    by 0x8C11857: ErrorTreePy::init_py(boost::python::list const&) (dtreemodule.cpp:37)
==1452==    by 0x8C0E9C1: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ErrorTreePy::*)(boost::python::list const&), boost::python::default_call_policies, boost::mpl::vector3<void, ErrorTreePy&, boost::python::list const&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94262C2: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 8
==1452==    at 0x8C12BFC: std::vector<ABDIndex<unsigned long, ABDStats>::bound_t, std::allocator<ABDIndex<unsigned long, ABDStats>::bound_t> > ABDTree::sort_by_group<__gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > > >(__gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > >, __gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > >, unsigned long, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > > const&) (new_allocator.h:120)
==1452==    by 0x8C0C19B: ABDTree::split(ABDNode*, unsigned long, double, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) (abd_tree.hpp:354)
==1452==    by 0x8C1576F: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:118)
==1452==    by 0x8C158DB: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:125)
==1452==    by 0x8C0D0D6: ABDTree::build() (abd_tree.hpp:317)
==1452==    by 0x8C0DF75: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ABDTree::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, ErrorTreePy&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94262C2: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==  Address 0x8161f48 is 8 bytes after a block of size 384 alloc'd
==1452==    at 0x4C2B0E0: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C10788: void std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> >::_M_emplace_back_aux<ScoreUnbiased const&>(ScoreUnbiased const&) (new_allocator.h:104)
==1452==    by 0x8C0DB26: ABDTree::init(std::vector<Rating, std::allocator<Rating> > const&) (stl_vector.h:923)
==1452==    by 0x8C11857: ErrorTreePy::init_py(boost::python::list const&) (dtreemodule.cpp:37)
==1452==    by 0x8C0E9C1: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ErrorTreePy::*)(boost::python::list const&), boost::python::default_call_policies, boost::mpl::vector3<void, ErrorTreePy&, boost::python::list const&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94262C2: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452== 
==1452== Invalid read of size 8
==1452==    at 0x8C12C04: std::vector<ABDIndex<unsigned long, ABDStats>::bound_t, std::allocator<ABDIndex<unsigned long, ABDStats>::bound_t> > ABDTree::sort_by_group<__gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > > >(__gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > >, __gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > >, unsigned long, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > > const&) (new_allocator.h:120)
==1452==    by 0x8C0C19B: ABDTree::split(ABDNode*, unsigned long, double, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) (abd_tree.hpp:354)
==1452==    by 0x8C1576F: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:118)
==1452==    by 0x8C158DB: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:125)
==1452==    by 0x8C0D0D6: ABDTree::build() (abd_tree.hpp:317)
==1452==    by 0x8C0DF75: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ABDTree::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, ErrorTreePy&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94262C2: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==  Address 0x8161f50 is 16 bytes after a block of size 384 alloc'd
==1452==    at 0x4C2B0E0: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C10788: void std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> >::_M_emplace_back_aux<ScoreUnbiased const&>(ScoreUnbiased const&) (new_allocator.h:104)
==1452==    by 0x8C0DB26: ABDTree::init(std::vector<Rating, std::allocator<Rating> > const&) (stl_vector.h:923)
==1452==    by 0x8C11857: ErrorTreePy::init_py(boost::python::list const&) (dtreemodule.cpp:37)
==1452==    by 0x8C0E9C1: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ErrorTreePy::*)(boost::python::list const&), boost::python::default_call_policies, boost::mpl::vector3<void, ErrorTreePy&, boost::python::list const&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94262C2: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452== 
==1452== Invalid write of size 8
==1452==    at 0x8C12AD4: std::vector<ABDIndex<unsigned long, ABDStats>::bound_t, std::allocator<ABDIndex<unsigned long, ABDStats>::bound_t> > ABDTree::sort_by_group<__gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > > >(__gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > >, __gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > >, unsigned long, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > > const&) (stl_algobase.h:336)
==1452==    by 0x8C0C19B: ABDTree::split(ABDNode*, unsigned long, double, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) (abd_tree.hpp:354)
==1452==    by 0x8C1576F: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:118)
==1452==    by 0x8C158DB: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:125)
==1452==    by 0x8C0D0D6: ABDTree::build() (abd_tree.hpp:317)
==1452==    by 0x8C0DF75: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ABDTree::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, ErrorTreePy&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94262C2: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==  Address 0x8161f40 is 0 bytes after a block of size 384 alloc'd
==1452==    at 0x4C2B0E0: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C10788: void std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> >::_M_emplace_back_aux<ScoreUnbiased const&>(ScoreUnbiased const&) (new_allocator.h:104)
==1452==    by 0x8C0DB26: ABDTree::init(std::vector<Rating, std::allocator<Rating> > const&) (stl_vector.h:923)
==1452==    by 0x8C11857: ErrorTreePy::init_py(boost::python::list const&) (dtreemodule.cpp:37)
==1452==    by 0x8C0E9C1: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ErrorTreePy::*)(boost::python::list const&), boost::python::default_call_policies, boost::mpl::vector3<void, ErrorTreePy&, boost::python::list const&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94262C2: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452== 
==1452== Invalid write of size 8
==1452==    at 0x8C12ADD: std::vector<ABDIndex<unsigned long, ABDStats>::bound_t, std::allocator<ABDIndex<unsigned long, ABDStats>::bound_t> > ABDTree::sort_by_group<__gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > > >(__gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > >, __gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > >, unsigned long, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > > const&) (stl_algobase.h:336)
==1452==    by 0x8C0C19B: ABDTree::split(ABDNode*, unsigned long, double, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) (abd_tree.hpp:354)
==1452==    by 0x8C1576F: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:118)
==1452==    by 0x8C158DB: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:125)
==1452==    by 0x8C0D0D6: ABDTree::build() (abd_tree.hpp:317)
==1452==    by 0x8C0DF75: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ABDTree::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, ErrorTreePy&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94262C2: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==  Address 0x8161f48 is 8 bytes after a block of size 384 alloc'd
==1452==    at 0x4C2B0E0: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C10788: void std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> >::_M_emplace_back_aux<ScoreUnbiased const&>(ScoreUnbiased const&) (new_allocator.h:104)
==1452==    by 0x8C0DB26: ABDTree::init(std::vector<Rating, std::allocator<Rating> > const&) (stl_vector.h:923)
==1452==    by 0x8C11857: ErrorTreePy::init_py(boost::python::list const&) (dtreemodule.cpp:37)
==1452==    by 0x8C0E9C1: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ErrorTreePy::*)(boost::python::list const&), boost::python::default_call_policies, boost::mpl::vector3<void, ErrorTreePy&, boost::python::list const&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94262C2: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452== 
==1452== Invalid write of size 8
==1452==    at 0x8C12AE7: std::vector<ABDIndex<unsigned long, ABDStats>::bound_t, std::allocator<ABDIndex<unsigned long, ABDStats>::bound_t> > ABDTree::sort_by_group<__gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > > >(__gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > >, __gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > >, unsigned long, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > > const&) (stl_algobase.h:336)
==1452==    by 0x8C0C19B: ABDTree::split(ABDNode*, unsigned long, double, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) (abd_tree.hpp:354)
==1452==    by 0x8C1576F: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:118)
==1452==    by 0x8C158DB: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:125)
==1452==    by 0x8C0D0D6: ABDTree::build() (abd_tree.hpp:317)
==1452==    by 0x8C0DF75: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ABDTree::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, ErrorTreePy&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94262C2: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==  Address 0x8161f50 is 16 bytes after a block of size 384 alloc'd
==1452==    at 0x4C2B0E0: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C10788: void std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> >::_M_emplace_back_aux<ScoreUnbiased const&>(ScoreUnbiased const&) (new_allocator.h:104)
==1452==    by 0x8C0DB26: ABDTree::init(std::vector<Rating, std::allocator<Rating> > const&) (stl_vector.h:923)
==1452==    by 0x8C11857: ErrorTreePy::init_py(boost::python::list const&) (dtreemodule.cpp:37)
==1452==    by 0x8C0E9C1: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ErrorTreePy::*)(boost::python::list const&), boost::python::default_call_policies, boost::mpl::vector3<void, ErrorTreePy&, boost::python::list const&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94262C2: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452== 
		[NODE 10]: Num.users: 5	Num.ratings: 61	Quality: -0.470824
		[NODE 10]: Maximum depth (3) reached. STOP.
		[NODE 11]: Num.users: 15	Num.ratings: 156	Quality: -28.9168
		[NODE 11]: Maximum depth (3) reached. STOP.
		[NODE 12]: Num.users: 960	Num.ratings: 9582	Quality: -9850.54
		[NODE 12]: Maximum depth (3) reached. STOP.
==1452== Invalid read of size 4
==1452==    at 0x56E90A: PyObject_GC_Del (in /usr/bin/python2.7)
==1452==    by 0x54B87B: ??? (in /usr/bin/python2.7)
==1452==    by 0x54B4D3: ??? (in /usr/bin/python2.7)
==1452==    by 0x4FDB95: PyDict_SetItem (in /usr/bin/python2.7)
==1452==    by 0x55A9E0: _PyModule_Clear (in /usr/bin/python2.7)
==1452==    by 0x4F2C35: PyImport_Cleanup (in /usr/bin/python2.7)
==1452==    by 0x42FA88: Py_Finalize (in /usr/bin/python2.7)
==1452==    by 0x46AC0F: Py_Main (in /usr/bin/python2.7)
==1452==    by 0x5076EC4: (below main) (libc-start.c:287)
==1452==  Address 0x7ec8020 is 0 bytes inside a block of size 80 free'd
==1452==    at 0x4C2C2BC: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C0EF7C: std::_Rb_tree<unsigned long, std::pair<unsigned long const, ABDStats>, std::_Select1st<std::pair<unsigned long const, ABDStats> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >::_M_erase(std::_Rb_tree_node<std::pair<unsigned long const, ABDStats> >*) (new_allocator.h:110)
==1452==    by 0x8C0AA8F: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.1] (stl_tree.h:715)
==1452==    by 0x840AA8E: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x840EFF7: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C0A7AD: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.0] (stl_vector.h:87)
==1452==    by 0x840C825: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x4E3F181: start_thread (pthread_create.c:312)
==1452==    by 0x515000C: clone (clone.S:111)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x54B76E: ??? (in /usr/bin/python2.7)
==1452==    by 0x54B4D3: ??? (in /usr/bin/python2.7)
==1452==    by 0x4FDB95: PyDict_SetItem (in /usr/bin/python2.7)
==1452==    by 0x55AA56: _PyModule_Clear (in /usr/bin/python2.7)
==1452==    by 0x4F2C35: PyImport_Cleanup (in /usr/bin/python2.7)
==1452==    by 0x42FA88: Py_Finalize (in /usr/bin/python2.7)
==1452==    by 0x46AC0F: Py_Main (in /usr/bin/python2.7)
==1452==    by 0x5076EC4: (below main) (libc-start.c:287)
==1452==  Address 0x5ebd020 is 64 bytes inside a block of size 80 free'd
==1452==    at 0x4C2C2BC: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C0EF59: std::_Rb_tree<unsigned long, std::pair<unsigned long const, ABDStats>, std::_Select1st<std::pair<unsigned long const, ABDStats> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >::_M_erase(std::_Rb_tree_node<std::pair<unsigned long const, ABDStats> >*) (new_allocator.h:110)
==1452==    by 0x8C0AA8F: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.1] (stl_tree.h:715)
==1452==    by 0x840AA8E: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x840F082: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C0A7AD: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.0] (stl_vector.h:87)
==1452==    by 0x840C825: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x4E3F181: start_thread (pthread_create.c:312)
==1452==    by 0x515000C: clone (clone.S:111)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x54B53B: ??? (in /usr/bin/python2.7)
==1452==    by 0x4FDB95: PyDict_SetItem (in /usr/bin/python2.7)
==1452==    by 0x55A9E0: _PyModule_Clear (in /usr/bin/python2.7)
==1452==    by 0x4F2C35: PyImport_Cleanup (in /usr/bin/python2.7)
==1452==    by 0x42FA88: Py_Finalize (in /usr/bin/python2.7)
==1452==    by 0x46AC0F: Py_Main (in /usr/bin/python2.7)
==1452==    by 0x5076EC4: (below main) (libc-start.c:287)
==1452==  Address 0x5ec0020 is 32 bytes inside a block of size 80 free'd
==1452==    at 0x4C2C2BC: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C0EF9F: std::_Rb_tree<unsigned long, std::pair<unsigned long const, ABDStats>, std::_Select1st<std::pair<unsigned long const, ABDStats> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >::_M_erase(std::_Rb_tree_node<std::pair<unsigned long const, ABDStats> >*) (new_allocator.h:110)
==1452==    by 0x8C0AA8F: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.1] (stl_tree.h:715)
==1452==    by 0x840AA8E: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x840EFF7: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C0A7AD: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.0] (stl_vector.h:87)
==1452==    by 0x84088EE: GOMP_parallel (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C14797: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) (d_tree.hpp:148)
==1452==    by 0x8C15505: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:108)
==1452==    by 0x8C158DB: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:125)
==1452==    by 0x8C0D0D6: ABDTree::build() (abd_tree.hpp:317)
==1452==    by 0x8C0DF75: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ABDTree::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, ErrorTreePy&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x4FDB95: PyDict_SetItem (in /usr/bin/python2.7)
==1452==    by 0x55A9E0: _PyModule_Clear (in /usr/bin/python2.7)
==1452==    by 0x4F2C35: PyImport_Cleanup (in /usr/bin/python2.7)
==1452==    by 0x42FA88: Py_Finalize (in /usr/bin/python2.7)
==1452==    by 0x46AC0F: Py_Main (in /usr/bin/python2.7)
==1452==    by 0x5076EC4: (below main) (libc-start.c:287)
==1452==  Address 0x6135020 is 48 bytes inside a block of size 80 free'd
==1452==    at 0x4C2C2BC: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C0EF7C: std::_Rb_tree<unsigned long, std::pair<unsigned long const, ABDStats>, std::_Select1st<std::pair<unsigned long const, ABDStats> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >::_M_erase(std::_Rb_tree_node<std::pair<unsigned long const, ABDStats> >*) (new_allocator.h:110)
==1452==    by 0x8C0AA8F: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.1] (stl_tree.h:715)
==1452==    by 0x840AA8E: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x840EFF7: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C0A7AD: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.0] (stl_vector.h:87)
==1452==    by 0x840C825: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x4E3F181: start_thread (pthread_create.c:312)
==1452==    by 0x515000C: clone (clone.S:111)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x56E90A: PyObject_GC_Del (in /usr/bin/python2.7)
==1452==    by 0x54B87B: ??? (in /usr/bin/python2.7)
==1452==    by 0x54B4D3: ??? (in /usr/bin/python2.7)
==1452==    by 0x5392FE: ??? (in /usr/bin/python2.7)
==1452==    by 0x5B2FF1: ??? (in /usr/bin/python2.7)
==1452==    by 0x4976DD: ??? (in /usr/bin/python2.7)
==1452==    by 0x4FDB95: PyDict_SetItem (in /usr/bin/python2.7)
==1452==    by 0x55A9E0: _PyModule_Clear (in /usr/bin/python2.7)
==1452==    by 0x4F2C35: PyImport_Cleanup (in /usr/bin/python2.7)
==1452==    by 0x42FA88: Py_Finalize (in /usr/bin/python2.7)
==1452==    by 0x46AC0F: Py_Main (in /usr/bin/python2.7)
==1452==    by 0x5076EC4: (below main) (libc-start.c:287)
==1452==  Address 0x7778020 is 0 bytes after a block of size 80 free'd
==1452==    at 0x4C2C2BC: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C0EF7C: std::_Rb_tree<unsigned long, std::pair<unsigned long const, ABDStats>, std::_Select1st<std::pair<unsigned long const, ABDStats> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >::_M_erase(std::_Rb_tree_node<std::pair<unsigned long const, ABDStats> >*) (new_allocator.h:110)
==1452==    by 0x8C0AA8F: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.1] (stl_tree.h:715)
==1452==    by 0x840AA8E: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x840EFF7: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C0A7AD: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.0] (stl_vector.h:87)
==1452==    by 0x840C825: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x4E3F181: start_thread (pthread_create.c:312)
==1452==    by 0x515000C: clone (clone.S:111)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x54B76E: ??? (in /usr/bin/python2.7)
==1452==    by 0x54B4D3: ??? (in /usr/bin/python2.7)
==1452==    by 0x5392FE: ??? (in /usr/bin/python2.7)
==1452==    by 0x5B2FF1: ??? (in /usr/bin/python2.7)
==1452==    by 0x538FE2: ??? (in /usr/bin/python2.7)
==1452==    by 0x5B2FDB: ??? (in /usr/bin/python2.7)
==1452==    by 0x4974C2: ??? (in /usr/bin/python2.7)
==1452==    by 0x5392FE: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D914A: ??? (in /usr/bin/python2.7)
==1452==    by 0x5392FE: ??? (in /usr/bin/python2.7)
==1452==    by 0x5391DE: ??? (in /usr/bin/python2.7)
==1452==  Address 0x613f020 is 16 bytes before a block of size 80 free'd
==1452==    at 0x4C2C2BC: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C0EF36: std::_Rb_tree<unsigned long, std::pair<unsigned long const, ABDStats>, std::_Select1st<std::pair<unsigned long const, ABDStats> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >::_M_erase(std::_Rb_tree_node<std::pair<unsigned long const, ABDStats> >*) (new_allocator.h:110)
==1452==    by 0x8C0AA8F: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.1] (stl_tree.h:715)
==1452==    by 0x840AA8E: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x840EFF7: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C0A7AD: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.0] (stl_vector.h:87)
==1452==    by 0x840C825: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x4E3F181: start_thread (pthread_create.c:312)
==1452==    by 0x515000C: clone (clone.S:111)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x5392FE: ??? (in /usr/bin/python2.7)
==1452==    by 0x5B2FF1: ??? (in /usr/bin/python2.7)
==1452==    by 0x4974C2: ??? (in /usr/bin/python2.7)
==1452==    by 0x5392FE: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D914A: ??? (in /usr/bin/python2.7)
==1452==    by 0x5392FE: ??? (in /usr/bin/python2.7)
==1452==    by 0x5391DE: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D914A: ??? (in /usr/bin/python2.7)
==1452==    by 0x497707: ??? (in /usr/bin/python2.7)
==1452==    by 0x4FDB95: PyDict_SetItem (in /usr/bin/python2.7)
==1452==    by 0x55A9E0: _PyModule_Clear (in /usr/bin/python2.7)
==1452==  Address 0x613f020 is 16 bytes before a block of size 80 free'd
==1452==    at 0x4C2C2BC: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C0EF36: std::_Rb_tree<unsigned long, std::pair<unsigned long const, ABDStats>, std::_Select1st<std::pair<unsigned long const, ABDStats> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >::_M_erase(std::_Rb_tree_node<std::pair<unsigned long const, ABDStats> >*) (new_allocator.h:110)
==1452==    by 0x8C0AA8F: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.1] (stl_tree.h:715)
==1452==    by 0x840AA8E: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x840EFF7: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C0A7AD: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.0] (stl_vector.h:87)
==1452==    by 0x840C825: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x4E3F181: start_thread (pthread_create.c:312)
==1452==    by 0x515000C: clone (clone.S:111)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x5392FE: ??? (in /usr/bin/python2.7)
==1452==    by 0x4FD99E: PyDict_SetItem (in /usr/bin/python2.7)
==1452==    by 0x55A9E0: _PyModule_Clear (in /usr/bin/python2.7)
==1452==    by 0x4F2C35: PyImport_Cleanup (in /usr/bin/python2.7)
==1452==    by 0x42FA88: Py_Finalize (in /usr/bin/python2.7)
==1452==    by 0x46AC0F: Py_Main (in /usr/bin/python2.7)
==1452==    by 0x5076EC4: (below main) (libc-start.c:287)
==1452==  Address 0x5f2e020 is 16 bytes after a block of size 80 free'd
==1452==    at 0x4C2C2BC: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C0EF7C: std::_Rb_tree<unsigned long, std::pair<unsigned long const, ABDStats>, std::_Select1st<std::pair<unsigned long const, ABDStats> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >::_M_erase(std::_Rb_tree_node<std::pair<unsigned long const, ABDStats> >*) (new_allocator.h:110)
==1452==    by 0x8C0AA8F: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.1] (stl_tree.h:715)
==1452==    by 0x840AA8E: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x840EFF7: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C0A7AD: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.0] (stl_vector.h:87)
==1452==    by 0x840C825: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x4E3F181: start_thread (pthread_create.c:312)
==1452==    by 0x515000C: clone (clone.S:111)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x54B53B: ??? (in /usr/bin/python2.7)
==1452==    by 0x4FDB95: PyDict_SetItem (in /usr/bin/python2.7)
==1452==    by 0x55AA56: _PyModule_Clear (in /usr/bin/python2.7)
==1452==    by 0x4F2C35: PyImport_Cleanup (in /usr/bin/python2.7)
==1452==    by 0x42FA88: Py_Finalize (in /usr/bin/python2.7)
==1452==    by 0x46AC0F: Py_Main (in /usr/bin/python2.7)
==1452==    by 0x5076EC4: (below main) (libc-start.c:287)
==1452==  Address 0x6579020 is 0 bytes after a block of size 96 free'd
==1452==    at 0x4C2C2BC: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C10823: void std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> >::_M_emplace_back_aux<ScoreUnbiased const&>(ScoreUnbiased const&) (new_allocator.h:110)
==1452==    by 0x8C12C3E: std::vector<ABDIndex<unsigned long, ABDStats>::bound_t, std::allocator<ABDIndex<unsigned long, ABDStats>::bound_t> > ABDTree::sort_by_group<__gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > > >(__gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > >, __gnu_cxx::__normal_iterator<ScoreUnbiased*, std::vector<ScoreUnbiased, std::allocator<ScoreUnbiased> > >, unsigned long, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > > const&) (stl_vector.h:923)
==1452==    by 0x8C0C19B: ABDTree::split(ABDNode*, unsigned long, double, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) (abd_tree.hpp:354)
==1452==    by 0x8C1576F: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:118)
==1452==    by 0x8C158DB: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:125)
==1452==    by 0x8C0D0D6: ABDTree::build() (abd_tree.hpp:317)
==1452==    by 0x8C0DF75: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ABDTree::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, ErrorTreePy&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94262C2: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x54B53B: ??? (in /usr/bin/python2.7)
==1452==    by 0x538FE2: ??? (in /usr/bin/python2.7)
==1452==    by 0x5392FE: ??? (in /usr/bin/python2.7)
==1452==    by 0x4FD99E: PyDict_SetItem (in /usr/bin/python2.7)
==1452==    by 0x55AA56: _PyModule_Clear (in /usr/bin/python2.7)
==1452==    by 0x4F2C35: PyImport_Cleanup (in /usr/bin/python2.7)
==1452==    by 0x42FA88: Py_Finalize (in /usr/bin/python2.7)
==1452==    by 0x46AC0F: Py_Main (in /usr/bin/python2.7)
==1452==    by 0x5076EC4: (below main) (libc-start.c:287)
==1452==  Address 0x6454020 is 0 bytes after a block of size 80 free'd
==1452==    at 0x4C2C2BC: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C0EF59: std::_Rb_tree<unsigned long, std::pair<unsigned long const, ABDStats>, std::_Select1st<std::pair<unsigned long const, ABDStats> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >::_M_erase(std::_Rb_tree_node<std::pair<unsigned long const, ABDStats> >*) (new_allocator.h:110)
==1452==    by 0x8C0AA8F: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.1] (stl_tree.h:715)
==1452==    by 0x840AA8E: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x840EFF7: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C0A7AD: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.0] (stl_vector.h:87)
==1452==    by 0x84088EE: GOMP_parallel (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C14797: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) (d_tree.hpp:148)
==1452==    by 0x8C15505: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:108)
==1452==    by 0x8C158DB: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:125)
==1452==    by 0x8C0D0D6: ABDTree::build() (abd_tree.hpp:317)
==1452==    by 0x8C0DF75: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ABDTree::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, ErrorTreePy&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x4FDB95: PyDict_SetItem (in /usr/bin/python2.7)
==1452==    by 0x55AA56: _PyModule_Clear (in /usr/bin/python2.7)
==1452==    by 0x4F2C35: PyImport_Cleanup (in /usr/bin/python2.7)
==1452==    by 0x42FA88: Py_Finalize (in /usr/bin/python2.7)
==1452==    by 0x46AC0F: Py_Main (in /usr/bin/python2.7)
==1452==    by 0x5076EC4: (below main) (libc-start.c:287)
==1452==  Address 0x6471020 is 16 bytes before a block of size 80 free'd
==1452==    at 0x4C2C2BC: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C0EF36: std::_Rb_tree<unsigned long, std::pair<unsigned long const, ABDStats>, std::_Select1st<std::pair<unsigned long const, ABDStats> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >::_M_erase(std::_Rb_tree_node<std::pair<unsigned long const, ABDStats> >*) (new_allocator.h:110)
==1452==    by 0x8C0AA8F: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.1] (stl_tree.h:715)
==1452==    by 0x840AA8E: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x840EFF7: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C0A7AD: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.0] (stl_vector.h:87)
==1452==    by 0x84088EE: GOMP_parallel (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C14797: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) (d_tree.hpp:148)
==1452==    by 0x8C15505: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:108)
==1452==    by 0x8C158DB: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:125)
==1452==    by 0x8C0D0D6: ABDTree::build() (abd_tree.hpp:317)
==1452==    by 0x8C0DF75: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ABDTree::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, ErrorTreePy&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x4FDB95: PyDict_SetItem (in /usr/bin/python2.7)
==1452==    by 0x55A9E0: _PyModule_Clear (in /usr/bin/python2.7)
==1452==    by 0x4F2CE9: PyImport_Cleanup (in /usr/bin/python2.7)
==1452==    by 0x42FA88: Py_Finalize (in /usr/bin/python2.7)
==1452==    by 0x46AC0F: Py_Main (in /usr/bin/python2.7)
==1452==    by 0x5076EC4: (below main) (libc-start.c:287)
==1452==  Address 0x6762020 is 16 bytes inside a block of size 80 free'd
==1452==    at 0x4C2C2BC: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C0EF7C: std::_Rb_tree<unsigned long, std::pair<unsigned long const, ABDStats>, std::_Select1st<std::pair<unsigned long const, ABDStats> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >::_M_erase(std::_Rb_tree_node<std::pair<unsigned long const, ABDStats> >*) (new_allocator.h:110)
==1452==    by 0x8C0AA8F: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.1] (stl_tree.h:715)
==1452==    by 0x840AA8E: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x840EFF7: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C0A7AD: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.0] (stl_vector.h:87)
==1452==    by 0x840C825: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x4E3F181: start_thread (pthread_create.c:312)
==1452==    by 0x515000C: clone (clone.S:111)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x56E90A: PyObject_GC_Del (in /usr/bin/python2.7)
==1452==    by 0x4D9178: ??? (in /usr/bin/python2.7)
==1452==    by 0x497707: ??? (in /usr/bin/python2.7)
==1452==    by 0x4FDB95: PyDict_SetItem (in /usr/bin/python2.7)
==1452==    by 0x55A9E0: _PyModule_Clear (in /usr/bin/python2.7)
==1452==    by 0x4F2CE9: PyImport_Cleanup (in /usr/bin/python2.7)
==1452==    by 0x42FA88: Py_Finalize (in /usr/bin/python2.7)
==1452==    by 0x46AC0F: Py_Main (in /usr/bin/python2.7)
==1452==    by 0x5076EC4: (below main) (libc-start.c:287)
==1452==  Address 0x6798020 is 0 bytes inside a block of size 80 free'd
==1452==    at 0x4C2C2BC: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C0EFC2: std::_Rb_tree<unsigned long, std::pair<unsigned long const, ABDStats>, std::_Select1st<std::pair<unsigned long const, ABDStats> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >::_M_erase(std::_Rb_tree_node<std::pair<unsigned long const, ABDStats> >*) (new_allocator.h:110)
==1452==    by 0x8C0AA8F: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.1] (stl_tree.h:715)
==1452==    by 0x840AA8E: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x840EFF7: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C0A7AD: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.0] (stl_vector.h:87)
==1452==    by 0x84088EE: GOMP_parallel (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C14797: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) (d_tree.hpp:148)
==1452==    by 0x8C15505: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:108)
==1452==    by 0x8C158DB: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:125)
==1452==    by 0x8C0D0D6: ABDTree::build() (abd_tree.hpp:317)
==1452==    by 0x8C0DF75: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ABDTree::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, ErrorTreePy&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x5392FE: ??? (in /usr/bin/python2.7)
==1452==    by 0x4FD99E: PyDict_SetItem (in /usr/bin/python2.7)
==1452==    by 0x55AA56: _PyModule_Clear (in /usr/bin/python2.7)
==1452==    by 0x4F2CE9: PyImport_Cleanup (in /usr/bin/python2.7)
==1452==    by 0x42FA88: Py_Finalize (in /usr/bin/python2.7)
==1452==    by 0x46AC0F: Py_Main (in /usr/bin/python2.7)
==1452==    by 0x5076EC4: (below main) (libc-start.c:287)
==1452==  Address 0x65a1020 is 32 bytes inside a block of size 48 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x539994: ??? (in /usr/bin/python2.7)
==1452==    by 0x5B2CA4: ??? (in /usr/bin/python2.7)
==1452==    by 0x5392FE: ??? (in /usr/bin/python2.7)
==1452==    by 0x4FD99E: PyDict_SetItem (in /usr/bin/python2.7)
==1452==    by 0x55AA56: _PyModule_Clear (in /usr/bin/python2.7)
==1452==    by 0x4F2CE9: PyImport_Cleanup (in /usr/bin/python2.7)
==1452==    by 0x42FA88: Py_Finalize (in /usr/bin/python2.7)
==1452==    by 0x46AC0F: Py_Main (in /usr/bin/python2.7)
==1452==    by 0x5076EC4: (below main) (libc-start.c:287)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x5392FE: ??? (in /usr/bin/python2.7)
==1452==    by 0x5B2FF1: ??? (in /usr/bin/python2.7)
==1452==    by 0x4FDB95: PyDict_SetItem (in /usr/bin/python2.7)
==1452==    by 0x55A9E0: _PyModule_Clear (in /usr/bin/python2.7)
==1452==    by 0x4F2CE9: PyImport_Cleanup (in /usr/bin/python2.7)
==1452==    by 0x42FA88: Py_Finalize (in /usr/bin/python2.7)
==1452==    by 0x46AC0F: Py_Main (in /usr/bin/python2.7)
==1452==    by 0x5076EC4: (below main) (libc-start.c:287)
==1452==  Address 0x6064020 is 64 bytes inside a block of size 80 free'd
==1452==    at 0x4C2C2BC: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C0EF9F: std::_Rb_tree<unsigned long, std::pair<unsigned long const, ABDStats>, std::_Select1st<std::pair<unsigned long const, ABDStats> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >::_M_erase(std::_Rb_tree_node<std::pair<unsigned long const, ABDStats> >*) (new_allocator.h:110)
==1452==    by 0x8C0AA8F: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.1] (stl_tree.h:715)
==1452==    by 0x840AA8E: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x840EFF7: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C0A7AD: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.0] (stl_vector.h:87)
==1452==    by 0x840C825: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x4E3F181: start_thread (pthread_create.c:312)
==1452==    by 0x515000C: clone (clone.S:111)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x54B53B: ??? (in /usr/bin/python2.7)
==1452==    by 0x5392FE: ??? (in /usr/bin/python2.7)
==1452==    by 0x5B2FF1: ??? (in /usr/bin/python2.7)
==1452==    by 0x4FDB95: PyDict_SetItem (in /usr/bin/python2.7)
==1452==    by 0x55A9E0: _PyModule_Clear (in /usr/bin/python2.7)
==1452==    by 0x4F2CE9: PyImport_Cleanup (in /usr/bin/python2.7)
==1452==    by 0x42FA88: Py_Finalize (in /usr/bin/python2.7)
==1452==    by 0x46AC0F: Py_Main (in /usr/bin/python2.7)
==1452==    by 0x5076EC4: (below main) (libc-start.c:287)
==1452==  Address 0x6064020 is 64 bytes inside a block of size 80 free'd
==1452==    at 0x4C2C2BC: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C0EF9F: std::_Rb_tree<unsigned long, std::pair<unsigned long const, ABDStats>, std::_Select1st<std::pair<unsigned long const, ABDStats> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >::_M_erase(std::_Rb_tree_node<std::pair<unsigned long const, ABDStats> >*) (new_allocator.h:110)
==1452==    by 0x8C0AA8F: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.1] (stl_tree.h:715)
==1452==    by 0x840AA8E: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x840EFF7: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C0A7AD: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.0] (stl_vector.h:87)
==1452==    by 0x840C825: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x4E3F181: start_thread (pthread_create.c:312)
==1452==    by 0x515000C: clone (clone.S:111)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x54B86D: ??? (in /usr/bin/python2.7)
==1452==    by 0x54B4D3: ??? (in /usr/bin/python2.7)
==1452==    by 0x4FDB95: PyDict_SetItem (in /usr/bin/python2.7)
==1452==    by 0x55AA56: _PyModule_Clear (in /usr/bin/python2.7)
==1452==    by 0x4F2CE9: PyImport_Cleanup (in /usr/bin/python2.7)
==1452==    by 0x42FA88: Py_Finalize (in /usr/bin/python2.7)
==1452==    by 0x46AC0F: Py_Main (in /usr/bin/python2.7)
==1452==    by 0x5076EC4: (below main) (libc-start.c:287)
==1452==  Address 0x5ef1020 is 3,008 bytes inside a block of size 3,049 free'd
==1452==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x54B76E: ??? (in /usr/bin/python2.7)
==1452==    by 0x54B4D3: ??? (in /usr/bin/python2.7)
==1452==    by 0x4FDB95: PyDict_SetItem (in /usr/bin/python2.7)
==1452==    by 0x55AA56: _PyModule_Clear (in /usr/bin/python2.7)
==1452==    by 0x4F2CE9: PyImport_Cleanup (in /usr/bin/python2.7)
==1452==    by 0x42FA88: Py_Finalize (in /usr/bin/python2.7)
==1452==    by 0x46AC0F: Py_Main (in /usr/bin/python2.7)
==1452==    by 0x5076EC4: (below main) (libc-start.c:287)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x5392FE: ??? (in /usr/bin/python2.7)
==1452==    by 0x5391DE: ??? (in /usr/bin/python2.7)
==1452==    by 0x465683: _PyImport_Fini (in /usr/bin/python2.7)
==1452==    by 0x42FA8D: Py_Finalize (in /usr/bin/python2.7)
==1452==    by 0x46AC0F: Py_Main (in /usr/bin/python2.7)
==1452==    by 0x5076EC4: (below main) (libc-start.c:287)
==1452==  Address 0x64cb020 is 0 bytes after a block of size 80 free'd
==1452==    at 0x4C2C2BC: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C0EF18: std::_Rb_tree<unsigned long, std::pair<unsigned long const, ABDStats>, std::_Select1st<std::pair<unsigned long const, ABDStats> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >::_M_erase(std::_Rb_tree_node<std::pair<unsigned long const, ABDStats> >*) (new_allocator.h:110)
==1452==    by 0x8C0AA8F: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.1] (stl_tree.h:715)
==1452==    by 0x840AA8E: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x840F082: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C0A7AD: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.0] (stl_vector.h:87)
==1452==    by 0x840C825: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x4E3F181: start_thread (pthread_create.c:312)
==1452==    by 0x515000C: clone (clone.S:111)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x5392FE: ??? (in /usr/bin/python2.7)
==1452==    by 0x5391DE: ??? (in /usr/bin/python2.7)
==1452==    by 0x5391DE: ??? (in /usr/bin/python2.7)
==1452==    by 0x465683: _PyImport_Fini (in /usr/bin/python2.7)
==1452==    by 0x42FA8D: Py_Finalize (in /usr/bin/python2.7)
==1452==    by 0x46AC0F: Py_Main (in /usr/bin/python2.7)
==1452==    by 0x5076EC4: (below main) (libc-start.c:287)
==1452==  Address 0x5dd0020 is 0 bytes after a block of size 80 free'd
==1452==    at 0x4C2C2BC: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C0EF02: std::_Rb_tree<unsigned long, std::pair<unsigned long const, ABDStats>, std::_Select1st<std::pair<unsigned long const, ABDStats> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >::_M_erase(std::_Rb_tree_node<std::pair<unsigned long const, ABDStats> >*) (new_allocator.h:110)
==1452==    by 0x8C0AA8F: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.1] (stl_tree.h:715)
==1452==    by 0x840AA8E: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x840EFF7: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C0A7AD: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.0] (stl_vector.h:87)
==1452==    by 0x840C825: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x4E3F181: start_thread (pthread_create.c:312)
==1452==    by 0x515000C: clone (clone.S:111)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x54B76E: ??? (in /usr/bin/python2.7)
==1452==    by 0x54B4D3: ??? (in /usr/bin/python2.7)
==1452==    by 0x539AAB: ??? (in /usr/bin/python2.7)
==1452==    by 0x5B914D: PyInterpreterState_Clear (in /usr/bin/python2.7)
==1452==    by 0x42FA95: Py_Finalize (in /usr/bin/python2.7)
==1452==    by 0x46AC0F: Py_Main (in /usr/bin/python2.7)
==1452==    by 0x5076EC4: (below main) (libc-start.c:287)
==1452==  Address 0x604e020 is 16 bytes after a block of size 80 free'd
==1452==    at 0x4C2C2BC: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C0EF59: std::_Rb_tree<unsigned long, std::pair<unsigned long const, ABDStats>, std::_Select1st<std::pair<unsigned long const, ABDStats> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >::_M_erase(std::_Rb_tree_node<std::pair<unsigned long const, ABDStats> >*) (new_allocator.h:110)
==1452==    by 0x8C0AA8F: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.1] (stl_tree.h:715)
==1452==    by 0x840AA8E: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x840F082: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C0A7AD: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.0] (stl_vector.h:87)
==1452==    by 0x840C825: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x4E3F181: start_thread (pthread_create.c:312)
==1452==    by 0x515000C: clone (clone.S:111)
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==1452==    by 0x5392FE: ??? (in /usr/bin/python2.7)
==1452==    by 0x5B2FF1: ??? (in /usr/bin/python2.7)
==1452==    by 0x538FE2: ??? (in /usr/bin/python2.7)
==1452==    by 0x5B2FDB: ??? (in /usr/bin/python2.7)
==1452==    by 0x538FE2: ??? (in /usr/bin/python2.7)
==1452==    by 0x5B2FDB: ??? (in /usr/bin/python2.7)
==1452==    by 0x538FE2: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D94BA: ??? (in /usr/bin/python2.7)
==1452==    by 0x5392FE: ??? (in /usr/bin/python2.7)
==1452==    by 0x5B916B: PyInterpreterState_Clear (in /usr/bin/python2.7)
==1452==    by 0x42FA95: Py_Finalize (in /usr/bin/python2.7)
==1452==  Address 0x6061020 is not stack'd, malloc'd or (recently) free'd
==1452== 
==1452== Invalid read of size 4
==1452==    at 0x53CFC2: PyGrammar_RemoveAccelerators (in /usr/bin/python2.7)
==1452==    by 0x42FAF3: Py_Finalize (in /usr/bin/python2.7)
==1452==    by 0x46AC0F: Py_Main (in /usr/bin/python2.7)
==1452==    by 0x5076EC4: (below main) (libc-start.c:287)
==1452==  Address 0x5f6f020 is 64 bytes inside a block of size 80 free'd
==1452==    at 0x4C2C2BC: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x8C0EF59: std::_Rb_tree<unsigned long, std::pair<unsigned long const, ABDStats>, std::_Select1st<std::pair<unsigned long const, ABDStats> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >::_M_erase(std::_Rb_tree_node<std::pair<unsigned long const, ABDStats> >*) (new_allocator.h:110)
==1452==    by 0x8C0AA8F: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.1] (stl_tree.h:715)
==1452==    by 0x840AA8E: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x840F082: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C0A7AD: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) [clone ._omp_fn.0] (stl_vector.h:87)
==1452==    by 0x840C825: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x4E3F181: start_thread (pthread_create.c:312)
==1452==    by 0x515000C: clone (clone.S:111)
==1452== 
==1452== 
==1452== HEAP SUMMARY:
==1452==     in use at exit: 1,481,022 bytes in 3,672 blocks
==1452==   total heap usage: 2,343,009 allocs, 2,339,337 frees, 229,983,557 bytes allocated
==1452== 
==1452== 520 bytes in 1 blocks are possibly lost in loss record 600 of 841
==1452==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x517A39: _PyObject_GC_NewVar (in /usr/bin/python2.7)
==1452==    by 0x4F3142: PyFrame_New (in /usr/bin/python2.7)
==1452==    by 0x56D462: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D9853: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D8378: ??? (in /usr/bin/python2.7)
==1452==    by 0x4F5D0A: ??? (in /usr/bin/python2.7)
==1452==    by 0x52E1E5: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x56D0A9: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D259B: ??? (in /usr/bin/python2.7)
==1452==    by 0x4F5BF4: ??? (in /usr/bin/python2.7)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452== 
==1452== 520 bytes in 1 blocks are possibly lost in loss record 601 of 841
==1452==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x517A39: _PyObject_GC_NewVar (in /usr/bin/python2.7)
==1452==    by 0x4F3142: PyFrame_New (in /usr/bin/python2.7)
==1452==    by 0x52CE52: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x56D0A9: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D9853: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D8378: ??? (in /usr/bin/python2.7)
==1452==    by 0x4F5D0A: ??? (in /usr/bin/python2.7)
==1452==    by 0x52E1E5: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x56D0A9: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D259B: ??? (in /usr/bin/python2.7)
==1452== 
==1452== 528 bytes in 1 blocks are possibly lost in loss record 605 of 841
==1452==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x517A39: _PyObject_GC_NewVar (in /usr/bin/python2.7)
==1452==    by 0x4F3142: PyFrame_New (in /usr/bin/python2.7)
==1452==    by 0x56CE48: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D259B: ??? (in /usr/bin/python2.7)
==1452==    by 0x4F5BF4: ??? (in /usr/bin/python2.7)
==1452==    by 0x54A327: PyObject_CallFunctionObjArgs (in /usr/bin/python2.7)
==1452==    by 0x5313CB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452==    by 0x579F0E: ??? (in /usr/bin/python2.7)
==1452== 
==1452== 536 bytes in 1 blocks are possibly lost in loss record 607 of 841
==1452==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x517A39: _PyObject_GC_NewVar (in /usr/bin/python2.7)
==1452==    by 0x4F3142: PyFrame_New (in /usr/bin/python2.7)
==1452==    by 0x55C32A: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==1452==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==1452== 
==1452== 536 bytes in 1 blocks are possibly lost in loss record 608 of 841
==1452==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x517A39: _PyObject_GC_NewVar (in /usr/bin/python2.7)
==1452==    by 0x4F3142: PyFrame_New (in /usr/bin/python2.7)
==1452==    by 0x56D462: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D259B: ??? (in /usr/bin/python2.7)
==1452==    by 0x4F5BF4: ??? (in /usr/bin/python2.7)
==1452==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x56D0A9: ??? (in /usr/bin/python2.7)
==1452==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==1452==    by 0x559B23: _PyCodec_Lookup (in /usr/bin/python2.7)
==1452==    by 0x5B5D68: ??? (in /usr/bin/python2.7)
==1452== 
==1452== 616 bytes in 1 blocks are possibly lost in loss record 617 of 841
==1452==    at 0x4C2CE8E: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x5AC787: _PyObject_GC_Resize (in /usr/bin/python2.7)
==1452==    by 0x4F31AF: PyFrame_New (in /usr/bin/python2.7)
==1452==    by 0x52CE52: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452== 
==1452== 624 bytes in 1 blocks are possibly lost in loss record 619 of 841
==1452==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x517A39: _PyObject_GC_NewVar (in /usr/bin/python2.7)
==1452==    by 0x4F3142: PyFrame_New (in /usr/bin/python2.7)
==1452==    by 0x52CE52: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x56D0A9: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D9853: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D8378: ??? (in /usr/bin/python2.7)
==1452==    by 0x4F5D0A: ??? (in /usr/bin/python2.7)
==1452==    by 0x52E1E5: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x56D0A9: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D259B: ??? (in /usr/bin/python2.7)
==1452==    by 0x4F5BF4: ??? (in /usr/bin/python2.7)
==1452== 
==1452== 736 bytes in 1 blocks are possibly lost in loss record 630 of 841
==1452==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x517A39: _PyObject_GC_NewVar (in /usr/bin/python2.7)
==1452==    by 0x4F3142: PyFrame_New (in /usr/bin/python2.7)
==1452==    by 0x52CE52: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452== 
==1452== 736 bytes in 1 blocks are possibly lost in loss record 631 of 841
==1452==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x517A39: _PyObject_GC_NewVar (in /usr/bin/python2.7)
==1452==    by 0x4F3142: PyFrame_New (in /usr/bin/python2.7)
==1452==    by 0x52CE52: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452== 
==1452== 816 bytes in 1 blocks are possibly lost in loss record 691 of 841
==1452==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x517A39: _PyObject_GC_NewVar (in /usr/bin/python2.7)
==1452==    by 0x4F3142: PyFrame_New (in /usr/bin/python2.7)
==1452==    by 0x52CE52: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x56D0A9: ??? (in /usr/bin/python2.7)
==1452==    by 0x4D9853: ??? (in /usr/bin/python2.7)
==1452==    by 0x54A327: PyObject_CallFunctionObjArgs (in /usr/bin/python2.7)
==1452==    by 0x52E8A2: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==1452==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==1452==    by 0x56D0A9: ??? (in /usr/bin/python2.7)
==1452== 
==1452== 912 bytes in 3 blocks are possibly lost in loss record 696 of 841
==1452==    at 0x4C2CC70: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1452==    by 0x4012E54: _dl_allocate_tls (dl-tls.c:296)
==1452==    by 0x4E3FDA0: pthread_create@@GLIBC_2.2.5 (allocatestack.c:589)
==1452==    by 0x840CD76: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x84088E9: GOMP_parallel (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==1452==    by 0x8C14797: DTree<ABDNode>::find_splitter(ABDNode const*, unsigned long&, double&, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >&, std::vector<double, std::allocator<double> >&, std::vector<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > >, std::allocator<std::map<unsigned long, ABDStats, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, ABDStats> > > > >&) (d_tree.hpp:148)
==1452==    by 0x8C15505: DTree<ABDNode>::gdt_r(ABDNode*) (d_tree.hpp:108)
==1452==    by 0x8C0D0D6: ABDTree::build() (abd_tree.hpp:317)
==1452==    by 0x8C0DF75: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (ABDTree::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, ErrorTreePy&> > >::operator()(_object*, _object*) (invoke.hpp:94)
==1452==    by 0x9427649: boost::python::objects::function::call(_object*, _object*) const (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x94279B7: ??? (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452==    by 0x9431C92: boost::python::handle_exception_impl(boost::function0<void>) (in /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0)
==1452== 
==1452== LEAK SUMMARY:
==1452==    definitely lost: 0 bytes in 0 blocks
==1452==    indirectly lost: 0 bytes in 0 blocks
==1452==      possibly lost: 7,080 bytes in 13 blocks
==1452==    still reachable: 1,473,942 bytes in 3,659 blocks
==1452==         suppressed: 0 bytes in 0 blocks
==1452== Reachable blocks (those to which a pointer was found) are not shown.
==1452== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==1452== 
==1452== For counts of detected and suppressed errors, rerun with: -v
==1452== Use --track-origins=yes to see where uninitialised values come from
==1452== ERROR SUMMARY: 868 errors from 101 contexts (suppressed: 0 from 0)
